name: Deploy blackjack function to existing Blackjack function-app.

on:
  [push]

env:
  AZURE_FUNCTIONAPP_NAME: blackjack-function-ta
  FUNCTION_NAME: blackjack-function-ta    
  SCRIPT_PATH: 'oppgave_11.ps1'   
  RESOURCE_GROUP: trond-workshop
  LOCATION: 'norwayeast'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: trond-prod
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Publish WebJob
      uses: srijken/azure-webjob-deploy@master
      with: 
        zip-file: blackjack-function.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 

#    - name: 'Run Azure Functions Action'
#      uses: Azure/functions-action@v1
#      id: fa
#      with:
#        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
#        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
#        creds: ${{ secrets.AZURE_CREDENTIALS }}
