# yaml to zip-deploy locally zipped files to azure function.
# Folder structure has to be as blackjack-function.zip is structured with:
# host.json in the parent directory.
# function.json and *.ps1 file in the folder with the same name as the AZURE_FUNCTIONAPP_NAME
# If you use a different filename then run.ps1, add scriptfile to the function.json.

name: Deploy blackjack function to existing Blackjack function-app

on:
  push:
    paths:
      - 'src/oppgave_13.ps1'

env:
  AZURE_FUNCTIONAPP_NAME: blackjack-function-ta

jobs:
  build-and-deploy:
    runs-on: windows-latest
    environment: prod-trond
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS }}

    - name: Publish WebJob
      uses: srijken/azure-webjob-deploy@master
      with: 
        zip-file: src/upload.zip
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} 